/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.equilend.simulator.model.recall;

import com.equilend.simulator.model.AcknowledgementType;
import com.equilend.simulator.model.venue.Venue;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Objects;
/**
 * Recall
 */



public class Recall {
  @JsonProperty("recallId")
  private String recallId = null;

  @JsonProperty("loanId")
  private String loanId = null;

  @JsonProperty("status")
  private RecallStatus status = null;

  @JsonProperty("executionVenue")
  private Venue executionVenue = null;

  @JsonProperty("openQuantity")
  private Integer openQuantity = null;

  @JsonProperty("quantity")
  private Integer quantity = null;

  @JsonProperty("recallDate")
  private LocalDate recallDate = null;

  @JsonProperty("recallDueDate")
  private LocalDate recallDueDate = null;

  @JsonProperty("lastUpdateDatetime")
  private OffsetDateTime lastUpdateDatetime = null;

  @JsonProperty("acknowledgementType")
  private AcknowledgementType acknowledgementType = null;

  public Recall recallId(String recallId) {
    this.recallId = recallId;
    return this;
  }

   /**
   * Get recallId
   * @return recallId
  **/
  @Schema(required = true, description = "")
  public String getRecallId() {
    return recallId;
  }

  public void setRecallId(String recallId) {
    this.recallId = recallId;
  }

  public Recall loanId(String loanId) {
    this.loanId = loanId;
    return this;
  }

   /**
   * Get loanId
   * @return loanId
  **/
  @Schema(required = true, description = "")
  public String getLoanId() {
    return loanId;
  }

  public void setLoanId(String loanId) {
    this.loanId = loanId;
  }

  public Recall status(RecallStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public RecallStatus getStatus() {
    return status;
  }

  public void setStatus(RecallStatus status) {
    this.status = status;
  }

  public Recall executionVenue(Venue executionVenue) {
    this.executionVenue = executionVenue;
    return this;
  }

   /**
   * Get executionVenue
   * @return executionVenue
  **/
  @Schema(description = "")
  public Venue getExecutionVenue() {
    return executionVenue;
  }

  public void setExecutionVenue(Venue executionVenue) {
    this.executionVenue = executionVenue;
  }

  public Recall openQuantity(Integer openQuantity) {
    this.openQuantity = openQuantity;
    return this;
  }

   /**
   * Get openQuantity
   * @return openQuantity
  **/
  @Schema(description = "")
  public Integer getOpenQuantity() {
    return openQuantity;
  }

  public void setOpenQuantity(Integer openQuantity) {
    this.openQuantity = openQuantity;
  }

  public Recall quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(required = true, description = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public Recall recallDate(LocalDate recallDate) {
    this.recallDate = recallDate;
    return this;
  }

   /**
   * Get recallDate
   * @return recallDate
  **/
  @Schema(description = "")
  public LocalDate getRecallDate() {
    return recallDate;
  }

  public void setRecallDate(LocalDate recallDate) {
    this.recallDate = recallDate;
  }

  public Recall recallDueDate(LocalDate recallDueDate) {
    this.recallDueDate = recallDueDate;
    return this;
  }

   /**
   * Get recallDueDate
   * @return recallDueDate
  **/
  @Schema(description = "")
  public LocalDate getRecallDueDate() {
    return recallDueDate;
  }

  public void setRecallDueDate(LocalDate recallDueDate) {
    this.recallDueDate = recallDueDate;
  }

  public Recall lastUpdateDatetime(OffsetDateTime lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
    return this;
  }

   /**
   * Get lastUpdateDatetime
   * @return lastUpdateDatetime
  **/
  @Schema(description = "")
  public OffsetDateTime getLastUpdateDatetime() {
    return lastUpdateDatetime;
  }

  public void setLastUpdateDatetime(OffsetDateTime lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
  }


  public AcknowledgementType getAcknowledgementType() {
    return acknowledgementType;
  }

  public void setAcknowledgementType(AcknowledgementType acknowledgementType) {
    this.acknowledgementType = acknowledgementType;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Recall recall = (Recall) o;
    return Objects.equals(this.recallId, recall.recallId) &&
        Objects.equals(this.loanId, recall.loanId) &&
        Objects.equals(this.status, recall.status) &&
        Objects.equals(this.executionVenue, recall.executionVenue) &&
        Objects.equals(this.openQuantity, recall.openQuantity) &&
        Objects.equals(this.quantity, recall.quantity) &&
        Objects.equals(this.recallDate, recall.recallDate) &&
        Objects.equals(this.recallDueDate, recall.recallDueDate) &&
        Objects.equals(this.lastUpdateDatetime, recall.lastUpdateDatetime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recallId, loanId, status, executionVenue, openQuantity, quantity, recallDate, recallDueDate, lastUpdateDatetime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Recall {\n");
    
    sb.append("    recallId: ").append(toIndentedString(recallId)).append("\n");
    sb.append("    loanId: ").append(toIndentedString(loanId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    executionVenue: ").append(toIndentedString(executionVenue)).append("\n");
    sb.append("    openQuantity: ").append(toIndentedString(openQuantity)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    recallDate: ").append(toIndentedString(recallDate)).append("\n");
    sb.append("    recallDueDate: ").append(toIndentedString(recallDueDate)).append("\n");
    sb.append("    lastUpdateDatetime: ").append(toIndentedString(lastUpdateDatetime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
