package com.equilend.simulator.model.trade.collateral;

public enum DescriptionCd {
    NONUSAGENCIES, AGENCIES, CANADIANBONDS, CANADIANPROVINCIALS, CORPORATES, DEBT, EMUDEBTAAA, EMUDEBT, AUSTRALIANEQUITIES, EQUITIES, GOVTDEBT105, G10DEBT, G3DEBT, G8DEBT, UKGILTS, GOVERNMENTISSUES, GOVERNMENTISSUESAAA, HIGHGRADEEQUITIES, INVESTMENTGRADECORPORATES, JAPANESEGOVERNMENTBONDS
}