/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.equilend.simulator.model.collateral;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets CollateralDescription
 */
public enum CollateralDescription {
    NONUSAGENCIES("NONUSAGENCIES"),
    AGENCIES("AGENCIES"),
    CANADIANBONDS("CANADIANBONDS"),
    CANADIANPROVINCIALS("CANADIANPROVINCIALS"),
    CORPORATES("CORPORATES"),
    DEBT("DEBT"),
    EMUDEBTAAA("EMUDEBTAAA"),
    EMUDEBT("EMUDEBT"),
    AUSTRALIANEQUITIES("AUSTRALIANEQUITIES"),
    EQUITIES("EQUITIES"),
    GOVTDEBT105("GOVTDEBT105"),
    G10DEBT("G10DEBT"),
    G3DEBT("G3DEBT"),
    G8DEBT("G8DEBT"),
    UKGILTS("UKGILTS"),
    GOVERNMENTISSUES("GOVERNMENTISSUES"),
    GOVERNMENTISSUESAAA("GOVERNMENTISSUESAAA"),
    HIGHGRADEEQUITIES("HIGHGRADEEQUITIES"),
    INVESTMENTGRADECORPORATES("INVESTMENTGRADECORPORATES"),
    JAPANESEGOVERNMENTBONDS("JAPANESEGOVERNMENTBONDS");

    private String value;

    CollateralDescription(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static CollateralDescription fromValue(String input) {
        for (CollateralDescription b : CollateralDescription.values()) {
            if (b.value.equals(input)) {
                return b;
            }
        }
        return null;
    }
}
